os: linux
dist: xenial
sudo: required
language: python

addons:
  postgresql: '10'

services:
- postgresql
- redis-server
- docker

cache: pip

python:
- '3.7'

before_install:
- mkdir -p $HOME/bin
- curl -Lf https://github.com/samuelcolvin/donkey-make/releases/download/v0.3/donk > $HOME/bin/donk
- chmod +x $HOME/bin/donk
- export PATH="$HOME/bin:$PATH"

install:
- donk install
- pip freeze

script:
- donk lint
- donk test
- donk build
- python setup.py build

after_success:
- ls -lha
- bash <(curl -s https://codecov.io/bash)

deploy:
- provider: pypi
  user: samuelcolvin
  password:
    secure: "B9y/DoUMwVAI+KkLJaj4+l/8j1bFkDDU1o9TmQYEmtl0tfVn8TfdRzALhoAhlgYjA+oDRTy+cMpJzcTqeIBzFiGYmWEk6i0zptpVMHFfvBKLhm6HNiWqQ1RItwnu50GSzZDcFDk2cMpw9QuhAZ3tsw/Gh9VRCzeGzh0JR6FszXGD12EkmP/cXdteJd/dXcyPLEYg9nfZeeeGyEL7OtjhQOhFGYT4vEEOf/vLi4Q3IhovPn/IcIGXTpaIFwQE3xeCAvkRhnNcocrbyreOv1dk+UD+50EGB1SGz0tmTgr/nJ44NrmZJ2p/cBNQZoJGUrnvcEOGIC2RpcLEkemsdA46DqB2Obh20FkKH4Gyk5dfn2zK/HOOuvNukpiAScFLnnS4N8AeRDpZmPxjB5h5p6GzItoe4u1PUneTjLfxEzdm/yKC0576VwpGuy/Khz4GlQAR0+jzDn3hEw36cJ54KcJkQ8qAquAoVE2su22az5dsr3LZKI4V1UtdShnevb4NvAvgQdpuAXeOZA56EBiK3ClLA8gFap/XumhESF+XNAKAIl9nR9sO8G6QraXwjDngC/zH59apNHQttui6n9ucRsUrboUV4bdFxT/3p6lg8ATJdqU/qdsbtnN5/MxAx1v/XSYZg8Rrv4Pm0nMbxbaynNd1Y8Evb1Z5DKf/B2vREICLYZY="
  distributions: sdist bdist_wheel
  skip_upload_docs: true
  on:
    tags: true
    python: 3.7
