#!/usr/bin/env bash
set -e
if [ "$MODE" != "PRODUCTION" ] && [ "$MODE" != "BETA" ] ; then
    echo "MODE not set to PRODUCTION or BETA, use 'source activate.prod.sh'"
    exit 2
fi
export RELEASE_DATE=`date`
the_command="docker-compose -f docker-compose.yml -p morpheus -f ${COMPOSE_EXTRA:-docker-compose.prod.yml} $@"
echo "Running '${the_command}'..."
eval ${the_command}
