#!/usr/bin/env bash
if [ "$MODE" != "PRODUCTION" ] && [ "$MODE" != "BETA" ] ; then
    echo "MODE not set to PRODUCTION, use 'source activate.prod.sh'"
    exit 2
fi
NAME='morpheus'
docker-machine create -d scaleway --scaleway-commercial-type 'C2M' --scaleway-name ${NAME} ${NAME}
