#!/usr/bin/env bash
set -e
THIS_DIR=$(dirname "$0")

echo "building morpheus image..."
export C=$(git rev-parse HEAD)
export BT=$(date)
docker build ${THIS_DIR}/../morpheus -t morpheus --build-arg COMMIT=$C --build-arg BUILD_TIME="$BT"

sed "s/{{HOST_NAME}}/${APP_HOST_NAME}/g; s/{{CLICK_HOST_NAME}}/${APP_CLICK_HOST_NAME}/g"\
 ${THIS_DIR}/../nginx/nginx.conf > ${THIS_DIR}/../nginx/_build.nginx.conf
echo "building nginx image..."
docker build ${THIS_DIR}/../nginx -t morpheus-nginx -q

echo ""
eval "${THIS_DIR}/compose up -d --build $@"
