name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: morpheus_test
        ports:
        - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    env:
      DATABASE_URL: 'postgresql://postgres:postgres@localhost:5432/morpheus_test'

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - name: install dependencies
      run: |
        make install
        pip freeze
    - name: lint
      run: make lint

    - name: test
      run: make test

    - name: codecov
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: '1b5eacd0-b422-4654-970d-84acdb03cf53'

  deploy:
    needs:
      - test
    if: "success() && startsWith(github.ref, 'refs/tags/')"
    runs-on: ubuntu-latest

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP: tc-morpheus

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --unshallow
      - run: git switch master
      - run: git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
      - run: git push heroku master
